### ISSUE TITLE
Matching VehiclePosition and TripUpdate

### ISSUE THREAD

**Issue by archerian** [ResidentMario/gtfs-tripify#1]
Capture and throw away vehicle updates that do not also have trip updates - is this a gtfs spec requirement or MTA specific?

**Comment by ResidentMario** [comment]
The GTFS-RT specification does not specifically stipulate that trip updates and vehicle updates should occur in pairs. In fact, it is more general than that, in that GTFS-RT spec allows transit agencies to provide only the subset of feed messages that the agency is operationally capable of:

> We would expect to receive trip updates for all trips you have scheduled that are realtime-capable.

> A single vehicle position should be provided for every vehicle that is capable of providing it.

Per [1](https://developers.google.com/transit/gtfs-realtime/guides/trip-updates), [2](https://developers.google.com/transit/gtfs-realtime/guides/vehicle-positions).

So technically speaking vehicle updates that occur without trip updates and vice versa are not in violation of the GTFS-RT specification.

However, the MTA feeds claim to provide both messages for every trip in the given line (if they didn't then the services built on this data, like the arrival clocks, would be pretty useless, as they would only cover a subset of trains). On manual inspection, I found that almost every message with either of these issues was a probable data error; that this occurs relatively rarely (maybe ~10% of snapshots have this issue at least once); and that there's little I can actually *do* with just a trip update or just a vehicle update. So to simplify my life I just drop those messages.
